### ISSUE TITLE
Error in convert_motifs for TFBStools-PFMatrixList

### ISSUE THREAD

**Issue by VangelisTheodorakis** [bjmt/universalmotif#3]
I am trying to query jaspar for all the Homo Sapiens TFs, but when I try to convert the PFMatrixList but I get the following error.

Error in if (mot_classes == classin) return(motifs) : 
  missing value where TRUE/FALSE needed

`library(JASPAR2018)`
`library(TFBSTools)`
`library(universalmotif)`

`opts <- list()`

`opts[["species"]] <- 9606`

`opts[["all_versions"]] <- TRUE`

`PFMatrixList.jaspar <- getMatrixSet(JASPAR2018, opts)`

`test <- convert_motifs(PFMatrixList.jaspar)`

**Comment by bjmt** [comment]
Think I've found the problem, thanks for letting me know. Try out version 1.3.68 of the package (from github or Bioc-devel in a couple days) and let me know if it's working for you.

**Comment by VangelisTheodorakis** [comment]
> Think I've found the problem, thanks for letting me know. Try out version 1.3.68 of the package (from github or Bioc-devel in a couple days) and let me know if it's working for you.

It throws error both with build = TRUE and build = FALSE.


```
if (!requireNamespace("remotes", quietly=TRUE))
  install.packages("remotes")
remotes::install_github("bjmt/universalmotif", build = FALSE)


Error: Failed to install 'universalmotif' from GitHub:
  Failed to `R CMD build` package, try `build = FALSE`.

if (!requireNamespace("remotes", quietly=FALSE))
  install.packages("remotes")
remotes::install_github("bjmt/universalmotif", build = FALSE)
```
**Edit:**
Even if I use the 1.3,61 version I still get the errors.
`install.packages("Downloads/universalmotif-1.3.61.tar.gz", repos = NULL, type="source")`

**Comment by bjmt** [comment]
Oops. When I tried to install it from github it gave an error about a missing file from the "collate" field. I've fixed this in version 1.3.69. Does this work for you?

**Comment by VangelisTheodorakis** [comment]
Well, available release versions end at 1.3.64...

**Comment by bjmt** [comment]
Sorry, I've been forgetting to tag my recent patches. Simply running `remotes::install_github("bjmt/universalmotif")` should do the trick.

**Comment by VangelisTheodorakis** [comment]
Well it still does not work and I tried both with
`remotes::install_github("bjmt/universalmotif")`
and
`install.packages("Downloads/universalmotif-1.3.69.tar.gz", repos = NULL, type="source")`

**Comment by bjmt** [comment]
Unfortunately I can't reproduce your error. Installing with `remotes::install_github("bjmt/universalmotif")` works fine on both my debian and macOS machines. Are there any error messages more informative than 'Failed to install'?

If not, then the best I can do is ask that you wait until the devel Bioconductor branch catches up (https://bioconductor.org/packages/devel/bioc/html/universalmotif.html). Once the version number listed in that link shows 1.3.69, then install from the devel branch as shown in the README. This'll happen either tomorrow or the day after.

**Comment by VangelisTheodorakis** [comment]
I am running R 3.6 on CentOS 7. And the Biocoductor image is still on the 1.2.1 version.
In addition both  gcc and g++ versions are 4.9.4. 

```
> install.packages("Downloads/universalmotif-1.3.69.tar.gz", repos = NULL, type="source")
Installing package into ‘/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
* installing *source* package ‘universalmotif’ ...
** using staged installation
** libs
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include" -I"/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include" -I/usr/local/include  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c RcppExports.cpp -o RcppExports.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include" -I"/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include" -I/usr/local/include  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c add_multifreq_helper.cpp -o add_multifreq_helper.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include" -I"/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include" -I/usr/local/include  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c compare_motifs_helper.cpp -o compare_motifs_helper.o
In file included from /data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread.h:11:0,
                 from compare_motifs_helper.cpp:2:
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/Thread.hpp: In lambda function:
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/Thread.hpp:42:19: error: parameter packs not expanded with ‘...’:
                 f(args...);
                   ^
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/Thread.hpp:42:19: note:         ‘args’
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/Thread.hpp:42:23: error: expansion pattern ‘args’ contains no argument packs
                 f(args...);
                       ^
In file included from /data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread.h:13:0,
                 from compare_motifs_helper.cpp:2:
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/ThreadPool.hpp: In member function ‘void RcppThread::ThreadPool::push(F&&, Args&& ...)’:
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/ThreadPool.hpp:127:31: error: expected ‘,’ before ‘...’ token
         jobs_.emplace([f, args...] { f(args...); });
                               ^
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/ThreadPool.hpp:127:31: error: expected identifier before ‘...’ token
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/ThreadPool.hpp:127:34: error: parameter packs not expanded with ‘...’:
         jobs_.emplace([f, args...] { f(args...); });
                                  ^
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/ThreadPool.hpp:127:34: note:         ‘args’
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/ThreadPool.hpp: In lambda function:
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/ThreadPool.hpp:127:44: error: expansion pattern ‘args’ contains no argument packs
         jobs_.emplace([f, args...] { f(args...); });
                                            ^
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/ThreadPool.hpp: In member function ‘std::future<decltype (f(args ...))> RcppThread::ThreadPool::pushReturn(F&&, Args&& ...)’:
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/ThreadPool.hpp:144:54: error: expected ‘,’ before ‘...’ token
     auto job = std::make_shared<jobPackage>([&f, args...] {
                                                      ^
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/ThreadPool.hpp:144:54: error: expected identifier before ‘...’ token
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/ThreadPool.hpp:144:57: error: parameter packs not expanded with ‘...’:
     auto job = std::make_shared<jobPackage>([&f, args...] {
                                                         ^
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/ThreadPool.hpp:144:57: note:         ‘args’
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/ThreadPool.hpp: In lambda function:
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/ThreadPool.hpp:145:22: error: expansion pattern ‘args’ contains no argument packs
         return f(args...);
                      ^
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/ThreadPool.hpp: In instantiation of ‘struct RcppThread::ThreadPool::push(F&&, Args&& ...) [with F = RcppThread::ThreadPool::parallelFor(ptrdiff_t, ptrdiff_t, F&&, size_t) [with F = compare_motifs_cpp(const List&, const std::vector<int>&, const std::vector<int>&, const string&, double, bool, std::vector<std::vector<double> >&, int, bool, double, bool, int, double, const std::vector<double>&, const string&)::__lambda13&; ptrdiff_t = long int; size_t = long unsigned int]::__lambda8&; Args = {const RcppThread::Batch&}]::__lambda5’:
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/ThreadPool.hpp:127:9:   required from ‘void RcppThread::ThreadPool::push(F&&, Args&& ...) [with F = RcppThread::ThreadPool::parallelFor(ptrdiff_t, ptrdiff_t, F&&, size_t) [with F = compare_motifs_cpp(const List&, const std::vector<int>&, const std::vector<int>&, const string&, double, bool, std::vector<std::vector<double> >&, int, bool, double, bool, int, double, const std::vector<double>&, const string&)::__lambda13&; ptrdiff_t = long int; size_t = long unsigned int]::__lambda8&; Args = {const RcppThread::Batch&}]’
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/ThreadPool.hpp:199:9:   required from ‘void RcppThread::ThreadPool::parallelFor(ptrdiff_t, ptrdiff_t, F&&, size_t) [with F = compare_motifs_cpp(const List&, const std::vector<int>&, const std::vector<int>&, const string&, double, bool, std::vector<std::vector<double> >&, int, bool, double, bool, int, double, const std::vector<double>&, const string&)::__lambda13&; ptrdiff_t = long int; size_t = long unsigned int]’
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/parallelFor.hpp:48:5:   required from ‘void RcppThread::parallelFor(ptrdiff_t, ptrdiff_t, F&&, size_t, size_t) [with F = compare_motifs_cpp(const List&, const std::vector<int>&, const std::vector<int>&, const string&, double, bool, std::vector<std::vector<double> >&, int, bool, double, bool, int, double, const std::vector<double>&, const string&)::__lambda13; ptrdiff_t = long int; size_t = long unsigned int]’
compare_motifs_helper.cpp:1404:18:   required from here
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/ThreadPool.hpp:127:27: error: using invalid field ‘RcppThread::ThreadPool::push(F&&, Args&& ...)::__lambda5::__args’
         jobs_.emplace([f, args...] { f(args...); });
                           ^
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/ThreadPool.hpp: In instantiation of ‘struct RcppThread::ThreadPool::push(F&&, Args&& ...) [with F = RcppThread::ThreadPool::parallelFor(ptrdiff_t, ptrdiff_t, F&&, size_t) [with F = compare_motifs_all_cpp(const List&, const string&, double, bool, std::vector<std::vector<double> >&, int, bool, double, bool, int, double, const std::vector<double>&, const string&)::__lambda14&; ptrdiff_t = long int; size_t = long unsigned int]::__lambda8&; Args = {const RcppThread::Batch&}]::__lambda5’:
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/ThreadPool.hpp:127:9:   required from ‘void RcppThread::ThreadPool::push(F&&, Args&& ...) [with F = RcppThread::ThreadPool::parallelFor(ptrdiff_t, ptrdiff_t, F&&, size_t) [with F = compare_motifs_all_cpp(const List&, const string&, double, bool, std::vector<std::vector<double> >&, int, bool, double, bool, int, double, const std::vector<double>&, const string&)::__lambda14&; ptrdiff_t = long int; size_t = long unsigned int]::__lambda8&; Args = {const RcppThread::Batch&}]’
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/ThreadPool.hpp:199:9:   required from ‘void RcppThread::ThreadPool::parallelFor(ptrdiff_t, ptrdiff_t, F&&, size_t) [with F = compare_motifs_all_cpp(const List&, const string&, double, bool, std::vector<std::vector<double> >&, int, bool, double, bool, int, double, const std::vector<double>&, const string&)::__lambda14&; ptrdiff_t = long int; size_t = long unsigned int]’
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/parallelFor.hpp:48:5:   required from ‘void RcppThread::parallelFor(ptrdiff_t, ptrdiff_t, F&&, size_t, size_t) [with F = compare_motifs_all_cpp(const List&, const string&, double, bool, std::vector<std::vector<double> >&, int, bool, double, bool, int, double, const std::vector<double>&, const string&)::__lambda14; ptrdiff_t = long int; size_t = long unsigned int]’
compare_motifs_helper.cpp:1463:18:   required from here
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/ThreadPool.hpp:127:27: error: using invalid field ‘RcppThread::ThreadPool::push(F&&, Args&& ...)::__lambda5::__args’
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/ThreadPool.hpp: In instantiation of ‘struct RcppThread::ThreadPool::push(F&&, Args&& ...) [with F = RcppThread::ThreadPool::parallelFor(ptrdiff_t, ptrdiff_t, F&&, size_t) [with F = pval_extractor(const std::vector<int>&, const std::vector<double>&, const std::vector<int>&, const std::vector<int>&, const string&, const std::vector<int>&, const std::vector<int>&, const std::vector<double>&, const std::vector<double>&, const std::vector<std::basic_string<char> >&, int)::__lambda15&; ptrdiff_t = long int; size_t = long unsigned int]::__lambda8&; Args = {const RcppThread::Batch&}]::__lambda5’:
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/ThreadPool.hpp:127:9:   required from ‘void RcppThread::ThreadPool::push(F&&, Args&& ...) [with F = RcppThread::ThreadPool::parallelFor(ptrdiff_t, ptrdiff_t, F&&, size_t) [with F = pval_extractor(const std::vector<int>&, const std::vector<double>&, const std::vector<int>&, const std::vector<int>&, const string&, const std::vector<int>&, const std::vector<int>&, const std::vector<double>&, const std::vector<double>&, const std::vector<std::basic_string<char> >&, int)::__lambda15&; ptrdiff_t = long int; size_t = long unsigned int]::__lambda8&; Args = {const RcppThread::Batch&}]’
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/ThreadPool.hpp:199:9:   required from ‘void RcppThread::ThreadPool::parallelFor(ptrdiff_t, ptrdiff_t, F&&, size_t) [with F = pval_extractor(const std::vector<int>&, const std::vector<double>&, const std::vector<int>&, const std::vector<int>&, const string&, const std::vector<int>&, const std::vector<int>&, const std::vector<double>&, const std::vector<double>&, const std::vector<std::basic_string<char> >&, int)::__lambda15&; ptrdiff_t = long int; size_t = long unsigned int]’
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/parallelFor.hpp:48:5:   required from ‘void RcppThread::parallelFor(ptrdiff_t, ptrdiff_t, F&&, size_t, size_t) [with F = pval_extractor(const std::vector<int>&, const std::vector<double>&, const std::vector<int>&, const std::vector<int>&, const string&, const std::vector<int>&, const std::vector<int>&, const std::vector<double>&, const std::vector<double>&, const std::vector<std::basic_string<char> >&, int)::__lambda15; ptrdiff_t = long int; size_t = long unsigned int]’
compare_motifs_helper.cpp:1826:18:   required from here
/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/RcppThread/include/RcppThread/ThreadPool.hpp:127:27: error: using invalid field ‘RcppThread::ThreadPool::push(F&&, Args&& ...)::__lambda5::__args’
make: *** [compare_motifs_helper.o] Error 1
ERROR: compilation failed for package ‘universalmotif’
* removing ‘/data/ouga04b/homes/theodora/R/x86_64-redhat-linux-gnu-library/3.6/universalmotif’
Warning in install.packages :
  installation of package ‘Downloads/universalmotif-1.3.69.tar.gz’ had non-zero exit status
```

**Comment by bjmt** [comment]
I'm guessing your version of g++ is out of date, since it seems to have trouble understanding C++11 lambdas. I found this issue on the RcppThread page which seems to be similar to yours: https://github.com/tnagler/RcppThread/issues/13 

This is probably the safest option for you if you are using Bioconductor packages from an image, especially if you're on linux.

**Comment by VangelisTheodorakis** [comment]
So for anyone trying to make this work, you need:

gcc version 7.4.0+
RcppThread R package
gsl-2.3 for the libgsl.so.19 library
and to install the 1.31.69 version of universalmotif
